Use version for MAAS profile verification
This is available across MASS 1.9 and 2.0.

diff --git a/add-node b/add-node
--- a/add-node
+++ b/add-node
@@ -17,7 +17,7 @@ export NETWORK=$2
 export MAAS_PROFILE=$3
 
 # This is a sanity check on connecting to the MAAS profile.
-maas $MAAS_PROFILE nodes list >/dev/null 2>&1 || die "cannot list MAAS nodes using profile '$MAAS_PROFILE'"
+maas $MAAS_PROFILE version read >/dev/null 2>&1 || die "MAAS verification failed using profile '$MAAS_PROFILE'"
 
 RUN() {
     echo "$1"
